### ISSUE TITLE
注意到不蒜子计数器使用了cookie，可否提供一份cookie使用用途说明？

### ISSUE THREAD

**Issue by No5972** [lbsha/busuanzi#1]
鉴于ibruce官网评论系统已无法使用，现在此提交issue。

按照要求我们网站需要针对所有出现的cookie进行用途声明。但ibruce官网未提供cookie说明，因此需要对其进行补充。谢谢。

**Comment by lbsha** [comment]
cookie是为了标识用户的唯一id的，用于统计uv
